name: release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set short sha
        run: echo "GITHUB_SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Login to Docker Hub (streamdal)
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.STREAMDAL_DOCKERHUB_USERNAME }}
          password: ${{ secrets.STREAMDAL_DOCKERHUB_TOKEN }}
      - name: Build docker image
        run: make docker/build